a:5:{i:0;s:665:"Error in file: "C:\xampp\htdocs\magento\app\code\local\Giang\Acc\sql\giang_acc_setup\install-1.0.0.php" - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'giang_acc' already exists, query was: CREATE TABLE `giang_acc` (
  `entity_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Catalogue ID' ,
  `catalogue_name` text NULL COMMENT 'Catalogue Name' ,
  `status` smallint NULL COMMENT 'Status' ,
  `vendor_name` text NULL COMMENT 'Vendor Name' ,
  `created_at` datetime NULL COMMENT 'Created At' ,
  `updated_at` datetime NULL COMMENT 'Updated At' ,
  PRIMARY KEY (`entity_id`)
) COMMENT='giang_acc' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci";i:1;s:940:"#0 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '1.0.8')
#2 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('1.0.8')
#3 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Model_App->_initModules()
#6 C:\xampp\htdocs\magento\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#7 C:\xampp\htdocs\magento\index.php(83): Mage::run('', 'store')
#8 {main}";s:3:"url";s:26:"/magento/giang/index/index";s:11:"script_name";s:18:"/magento/index.php";s:4:"skin";s:7:"default";}